name: piano_sample
description: Piano App Sample

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/piano_bg.jpg
   - assets/C3.wav
   - assets/C4.wav
   - assets/C5.wav
   - assets/C6.wav
   - assets/D3.wav
   - assets/D4.wav
   - assets/D5.wav
   - assets/D6.wav
   - assets/Db3.wav
   - assets/Db4.wav
   - assets/Db5.wav
   - assets/Db6.wav
   - assets/E3.wav
   - assets/E4.wav
   - assets/E5.wav
   - assets/E6.wav
   - assets/Eb3.wav
   - assets/Eb4.wav
   - assets/Eb5.wav
   - assets/Eb6.wav
   - assets/F3.wav
   - assets/F4.wav
   - assets/F5.wav
   - assets/F6.wav
   - assets/G3.wav
   - assets/G4.wav
   - assets/G5.wav
   - assets/G6.wav
   - assets/Gb3.wav
   - assets/Gb4.wav
   - assets/Gb5.wav
   - assets/Gb6.wav
   - assets/A3.wav
   - assets/A4.wav
   - assets/A5.wav
   - assets/A6.wav
   - assets/Ab3.wav
   - assets/Ab4.wav
   - assets/Ab5.wav
   - assets/Ab6.wav
   - assets/B3.wav
   - assets/B4.wav
   - assets/B5.wav
   - assets/B6.wav
   - assets/Bb3.wav
   - assets/Bb4.wav
   - assets/Bb5.wav
   - assets/Bb6.wav
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
